#include "krkrvita/phase1_filter.hpp"

#include "krkrvita/filter_heuristic.hpp"
#include "krkrvita/game.hpp"
#include "krkrvita/xp3_archive.hpp"

#include <algorithm>
#include <filesystem>
#include <iterator>
#include <stdexcept>
#include <vector>

namespace krkrvita {

std::optional<Phase1FilterResult> infer_phase1_filter(
    const std::string& game_path, std::string* error) {
    try {
        const GameDescriptor game = GameScanner::scan(
            std::filesystem::path(game_path), GameScanMode::ArchivesOnly);
        if (game.archives.empty()) {
            throw std::runtime_error("selected game contains no XP3 archives");
        }

        std::vector<FilterSample> samples;
        std::string last_archive_error;
        for (const GameFile& archive_file : game.archives) {
            std::string archive_error;
            auto archive = Xp3Archive::open(archive_file.path, &archive_error);
            if (!archive) {
                last_archive_error = archive_error;
                continue;
            }
            auto archive_samples = collect_xp3_filter_samples(
                *archive, 12, nullptr, &archive_error);
            if (archive_samples.empty()) {
                if (!archive_error.empty()) last_archive_error = archive_error;
                continue;
            }
            samples.insert(samples.end(),
                           std::make_move_iterator(archive_samples.begin()),
                           std::make_move_iterator(archive_samples.end()));
            if (samples.size() >= 96) break;
        }
        if (samples.size() > 96) samples.resize(96);
        if (samples.empty()) {
            throw std::runtime_error(last_archive_error.empty()
                ? "XP3 archives contain no usable Phase 1 samples"
                : last_archive_error);
        }

        const FilterInferenceResult analysis = FilterHeuristic::analyze(samples);
        if (!analysis.rule) {
            const char* phase = analysis.disposition ==
                FilterInferenceDisposition::RequiresExecutableAnalysis
                ? "phase 2 executable analysis required: "
                : "insufficient archive evidence: ";
            throw std::runtime_error(std::string(phase) + analysis.reason);
        }

        const FilterRule& rule = *analysis.rule;
        std::size_t recognized = 0;
        for (const FilterSample& sample : samples) {
            std::vector<std::uint8_t> decoded = sample.bytes;
            rule.apply(sample.hash, sample.offset, decoded, sample.filename);
            if (FilterHeuristic::score_plaintext(sample.filename, decoded) >= 80) {
                ++recognized;
            }
        }
        const std::size_t required = std::max<std::size_t>(
            std::min<std::size_t>(2, samples.size()), (samples.size() + 2) / 3);
        if (recognized < required) {
            throw std::runtime_error(
                "inferred rule failed native archive verification");
        }

        Phase1FilterResult result;
        result.archive_fingerprint = game.fingerprint.substr(0, 16);
        result.rule_name = rule.name();
        result.script =
            "// Generated by the Kirikiri Vita Phase 1 archive heuristic.\n" +
            rule.to_tjs();
        result.samples = samples.size();
        result.recognized = recognized;
        return result;
    } catch (const std::exception& exception) {
        if (error) *error = exception.what();
        return std::nullopt;
    }
}

} // namespace krkrvita
